name: Python CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src tests

    - name: Format with Black
      run: |
        pip install black
        black --check src tests

    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: Generate coverage report
      run: |
        pip install coverage
        coverage run -m pytest
        coverage report -m
